### ISSUE TITLE
Trying to use gyp...

### ISSUE THREAD

**Issue by H4wak** [enginetrouble/gyp-getting-started#1]
Hello, i tried to use gyp but i have some problems...

I think i  installed gyp succefully with the setup.py in the repo of gyp-master. But where can i use that : tools/gyp/gyp build/trivial.gyp --depth=. -f msvs -G msvs_version=2013
??

I don't really understand how GYP is really working.. Thanks !

**Comment by mogemimi** [comment]
Hi @H4wak

It seems the problem is a path separator issue. Are you Windows default command prompt user? If so, could you try to replace the forward slashes (`/`) with backslashes (`\`) and try again:
```shell
tools\gyp\gyp build/trivial.gyp --depth=. -f msvs -G msvs_version=2013
```

Under Windows command prompt, `tools\gyp\gyp` is same as `tools\gyp\gyp.bat` file. So you can also run the following command explicitly:
```shell
tools\gyp\gyp.bat build/trivial.gyp --depth=. -f msvs -G msvs_version=2013
```

Or if that's still not good, please run the 'gyp_main.py' script using `python` instead of `tools/gyp/gyp`:
```shell
python tools/gyp/gyp_main.py build/trivial.gyp --depth=. -f msvs -G msvs_version=2013
```

**Comment by H4wak** [comment]
Thanks @mogemimi !
I have few question, first i don't know if gyp is installed or not. When i run the setup for installing it, i have a lot of "SyntaxError: invalid syntax" or "missing parentheses in call to "print" i don't know if that can affect the installation or not... 
Second, i can't use the "python" command, i just can use "py" for python. It's important too or not ? 
Sorry for all of theses questions, I don't know how to code with Windows ! (Linux user :+1: )

Only the last command line is "working", i have a Syntax Error here : "except ImportError, e:"
                                                                                                                                          ^
The first say : 'tools' is not a internal command or exe or ect..
The second say : 'python'  is not a internal command or exe or ect..

Thanks for helping me ! :)

**Comment by H4wak** [comment]
I had Python 3.5 and gyp need Python 2.x... 
I tried :
gyp build/trivial.gyp --depth=. -f msvs_version=2013
and I have an error : 
ImportError : No module named msvs_version=2013

any idea ?

**Comment by mogemimi** [comment]
Glad to here that! :tada: 
Exactly! GYP use Python 2, but is not supported Python 3 at present.

Well 'second question' is too difficult to answer because I'm not python export.
So I've just installed Linux (Ubuntu) in a virtual machine now and tried to run the `setup.py` and `gyp_main.py` with `py` command, like this:
```shell
$ alias python=''
$ alias py='/usr/bin/python'
$ alias sudo='sudo '
```
**(1) Install setuptools**
```shell
$ wget https://bootstrap.pypa.io/ez_setup.py -O - | py - --user
```
**(2) Run the `setup.py`**
```
$ sudo py setup.py install
running install
running bdist_egg
...
Installing gyp script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/gyp-0.1-py2.7.egg
Processing dependencies for gyp==0.1
Finished processing dependencies for gyp==0.1
```
**(3) Make sure if gyp is installed**
```shell
$ type -a gyp
gyp is /usr/local/bin/gyp
```
**(4) Generate MSVS project**
```shell
$ py tools/gyp/gyp_main.py build/trivial.gyp --depth=. -f msvs -G msvs_version=2013
Warning: Missing input files:
build/..\src\Entity.cpp
build/..\test\EntityTest.cpp
```

I hope this will help generating your projects :relieved:

**Comment by H4wak** [comment]
I found how to use the `python` keyword ! It was in Windows' environment varables, in the variable "path", just add the path of your Python and it's OK ! Same for the `gyp` command ! :smirk: 

So I created the Visual Studio project and it's work well ! Just a little thing for the debugging just add in common.gypi file a line about the GenerateDebugInformation :
 `'Link': { `
          `  'GenerateDebugInformation' : 'true', ` <--- That line
      `      #'LinkIncremental': 'true', # /INCREMENTAL
          },`

With that line, we can use the Windows Debugger in Visual Studio ! 

Thanks a lot, gyp is much easier now ! :smile:

**Comment by mogemimi** [comment]
Yay! Congratulations! :beers: 

I just updated [readme file](https://github.com/enginetrouble/gyp-getting-started/blob/master/README.md) and added `GenerateDebugInformation` property to enable Visual Studio debugging in `common.gypi` (This commit: https://github.com/enginetrouble/gyp-getting-started/commit/ca5d09c2df9bd35561e95252da13427ce0e0e1ff)

Thanks for reporting, and please ask again if you have questions.
Have a nice day.
